#!/bin/bash

run="composer install"

if [ $# = 0 ] || [[ $1 != dev* ]]; then
    run="$run --optimize-autoloader --no-dev && php artisan config:cache && php artisan route:cache && php artisan view:cache";
else
    run="$run && php artisan config:clear && php artisan route:clear && php artisan view:clear";
fi

docker run --rm \
    --volume $HOME/.composer:/tmp \
    --volume $PWD/src:/app \
    --entrypoint /bin/bash \
    composer \
    -c "$run"

docker-compose up -d
